spring:
  profiles:
    active: dev
  application:
    name: startup-connect
  datasource:
    url: jdbc:mysql://localhost:3306/startupconnect?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "$Hubh@123"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    access-token-expiration-ms: 86400000
    refresh-token-expiration-ms: 604800000
  security:
    email-verification-expiration-ms: 86400000
    password-reset-expiration-ms: 3600000

aws:
  access-key: dev-access-key
  secret-key: dev-secret-key
  region: us-east-1
  s3:
    bucket: startupconnect-files

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
